-- =============================================================================
-- Neon / PostgreSQL — ejecuta TODO este script en el SQL Editor de Neon (una vez).
-- Hibernate con ddl-auto=update también puede crear tablas; este script fija el esquema.
-- =============================================================================

DROP TABLE IF EXISTS jugador CASCADE;
DROP TABLE IF EXISTS club_competicion CASCADE;
DROP TABLE IF EXISTS club CASCADE;
DROP TABLE IF EXISTS competicion CASCADE;
DROP TABLE IF EXISTS entrenador CASCADE;
DROP TABLE IF EXISTS asociacion CASCADE;

CREATE TABLE asociacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  pais varchar(80) NOT NULL,
  presidente varchar(160) NOT NULL
);

CREATE TABLE entrenador (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  apellido varchar(120) NOT NULL,
  edad integer NOT NULL,
  nacionalidad varchar(80) NOT NULL
);

CREATE TABLE competicion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  monto_premio double precision NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL
);

CREATE TABLE club (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  id_entrenador bigint NOT NULL,
  id_asociacion bigint NOT NULL,
  CONSTRAINT uk_club_entrenador UNIQUE (id_entrenador),
  CONSTRAINT fk_club_entrenador FOREIGN KEY (id_entrenador) REFERENCES entrenador (id) ON DELETE CASCADE,
  CONSTRAINT fk_club_asociacion FOREIGN KEY (id_asociacion) REFERENCES asociacion (id)
);

CREATE TABLE club_competicion (
  id_club bigint NOT NULL,
  id_competicion bigint NOT NULL,
  PRIMARY KEY (id_club, id_competicion),
  CONSTRAINT fk_cc_club FOREIGN KEY (id_club) REFERENCES club (id) ON DELETE CASCADE,
  CONSTRAINT fk_cc_competicion FOREIGN KEY (id_competicion) REFERENCES competicion (id) ON DELETE CASCADE
);

CREATE TABLE jugador (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  apellido varchar(120) NOT NULL,
  numero integer NOT NULL,
  posicion varchar(64) NOT NULL,
  id_club bigint NOT NULL,
  CONSTRAINT fk_jugador_club FOREIGN KEY (id_club) REFERENCES club (id) ON DELETE CASCADE
);
